---

- name: Install or upgrade bash modifications for current user
  block:
  - name: Create user bash configuration directory
    file:
      path:  /home/{{ lookup('env','USER') }}/.config/bash
      state: directory

  - name: Install latest user bash common file
    copy:
      src: common.bash
      dest: /home/{{ lookup('env','USER') }}/.config/bash/common.bash
      force: yes

  - name: Source user bash common file
    lineinfile:
      path: /home/{{ lookup('env','USER') }}/.bashrc
      state: present
      regexp: '^source.*\.config/bash/common\.bash$'
      line: source /home/{{ lookup('env','USER') }}/.config/bash/common.bash

- name: Install or upgrade bash modifications for root user
  block:
  - name: Create root bash configuration directory
    file:
      path:  /root/.config/bash
      state: directory

  - name: Install latest root bash common file
    copy:
      src: common.bash
      dest: /root/.config/bash/common.bash
      force: yes

  - name: Source root bash common file
    lineinfile:
      path: /root/.bashrc
      state: present
      regexp: '^source.*\.config/bash/common\.bash$'
      line: source /root/.config/bash/common.bash
  become: yes

