---

- name: Latest packages
  package:
    name:
      - vim-enhanced
      - openvpn
      - tmux
      - git
      - make
      - socat
      - ansible
      - openssh-clients
      - net-snmp-utils
      - jq
      - fping
      - podman
      - python3
      - python3-virtualenv
      - gcc
      - nmap
    state: latest  
  become: yes

- name: Absent packages
  package:
    name:
      - vim-minimal
    state: absent
  become: yes

- name: Making sure user directories are existing
  block:
  - name: ~/.config/systemd/user
    file:
      path:  /home/{{ lookup('env','USER') }}/.config/systemd/user
      state: directory

  - name: ~/bin
    file:
      path:  /home/{{ lookup('env','USER') }}/bin
      state: directory
  
- name: Making sure root directories are existing
  block:
  - name: ~/.config
    file:
      path:  /root/.config
      state: directory
  become: yes
